---
title: "Week 13 (Lectures & Homework)"
author: "Kauanoe Greene"
date: "2024-12-03"
output: github_document
---

```{r setup, include=FALSE}

# Let us set up Rmarkdown file
knitr::opts_chunk$set(echo = TRUE, 
                      message = FALSE, 
                      warning = FALSE, 
                      fig.path = "../Output/")
```

# Libraries  

```{r}
library(tidyverse)
library(here)
library(dplyr)
```

# Lecture: For Loops!     

```{r}
# for loops!  
# one way to run an iterative process  
# index in statement  
# command looks like:
# for( index in sequence) {command to repeat}
```

```{r}
# using loops to read in multiple .csv files  
testdata<-read_csv(here("Week_13", "data", "cond_data","011521_CT316_1pcal.csv"))
glimpse(testdata)
```

```{r}
# list files in a directory  
# point to the location on the computer of the folder
CondPath<-here("Week_13", "data", "cond_data")
# list all the files in that path with a specific pattern
# In this case we are looking for everything that has a .csv in the filename
# you can use regex to be more specific if you are looking for certain patterns in filenames
files <- dir(path = CondPath,pattern = ".csv")
files
```
```{r}

# pre-allocate space for the loop  
# make an empty dataframe that has one row for each file and 3 columns
 cond_data<-tibble(filename =  rep(NA, length(files)),  # column name for year
                   mean_temp = rep(NA, length(files)), # column name for the mean temperature
                   mean_sal = rep(NA, length(files)), # column name for the mean salinity
                   ) # column name for the year name
cond_data
```


```{r}
# for loop  
raw_data<-read_csv(paste0(CondPath,"/",files[1])) # test by reading in the first file and see if it works
head(raw_data)
```

```{r}

# turn it into a for loop  
for (i in 1:length(files)){ # loop over 1:3 the number of files
}

# add in the loop over the raw data  

for (i in 1:length(files)){ # loop over 1:3 the number of files 
raw_data<-read_csv(paste0(CondPath,"/",files[i]))
glimpse(raw_data)
}
```

```{r}

# add in the columns  
for (i in 1:length(files)){ # loop over 1:3 the number of files 
raw_data<-read_csv(paste0(CondPath,"/",files[i]))
#glimpse(raw_data)
cond_data$filename[i]<-files[i]
} 
cond_data
```

```{r}

# add in means  
for (i in 1:length(files)){ # loop over 1:3 the number of files 
raw_data<-read_csv(paste0(CondPath,"/",files[i]))
#glimpse(raw_data)
cond_data$filename[i]<-files[i]
cond_data$mean_temp[i]<-mean(raw_data$Temperature, na.rm =TRUE)
cond_data$mean_sal[i]<-mean(raw_data$Salinity, na.rm =TRUE)
} 
cond_data
```

# Lecture: Maps!  

```{r}

# the pattern of looping over a vector.  
# map() makes a list.
# map_lgl() makes a logical vector.
# map_int() makes an integer vector.
# map_dbl() makes a double vector.
# map_chr() makes a character vector.
# map_df() makes a dataframe

# Each function takes a vector as input, applies a function to each piece, and then returns a new vector that’s the same length (and has the same names) as the input.
```


```{r}
# use a canned function that already exists


1:10 %>% # a vector from 1 to 10 (we are going to do this 10 times) %>% # the vector to iterate over
  map(rnorm, n = 15) # calculate 15 random numbers based on a normal distribution in a list
```

```{r}

# calculate the mean from each list  

1:10 %>% # a vector from 1 to 10 (we are going to do this 10 times) %>% # the vector to iterate over
  map(rnorm, n = 15)  %>% # calculate 15 random numbers based on a normal distribution in a list 
  map_dbl(mean) # calculate the mean. It is now a vector which is type "double"
```

```{r}

# make your own function  

1:10 %>% # list 1:10
  map(function(x) rnorm(15, x)) %>% # make your own function
  map_dbl(mean)
```
```{r}

# Use a formula when you want to change the arguments within the function  

1:10 %>%
  map(~ rnorm(15, .x)) %>% # changes the arguments inside the function
  map_dbl(mean)

```


```{r}

# bring in files using purrr instead of a for loop 
# point to the location on the computer of the folder

CondPath<-here("Week_13", "data", "cond_data")
files <- dir(path = CondPath,pattern = ".csv")
files
```

```{r}

# Or, we can get the full file names in one less step by doing this...  

files <- dir(path = CondPath,pattern = ".csv", full.names = TRUE)
#save the entire path name
files
```

```{r}

# read in the files  

data<-files %>%
  set_names()%>% # set's the id of each list to the file name
  map_df(read_csv,.id = "filename") # map everything to a dataframe and put the id in a column called filename
data
```

```{r}

# calculate means  

data<-files %>%
  set_names()%>% # set's the id of each list to the file name
  map_df(read_csv,.id = "filename") %>% # map everything to a dataframe and put the id in a column called filename
  group_by(filename) %>%
  summarise(mean_temp = mean(Temperature, na.rm = TRUE),
            mean_sal = mean(Salinity,na.rm = TRUE))
```

# Homework  
```{r}

# Homework  

# You have a set of 4 .csv files in data/homework. Each of these files is a timeseries of temperature and light data collected in tide pools in Oregon by Jenn Fields. 
# Your goal is to bring in all 4 files and calculate the mean and standard deviation of both temperature (Temp.C) and light (Intensity.lux) for each tide pool. 

# Use both a for loop and map() functions in your script. (Basically, do it twice). Due Tuesday at 1pm.

```


```{r}

# data upload all .csv files below  

TP1<-read_csv(here("Week_13", "Data", "homework", "TP1.csv"))
TP2<-read_csv(here("Week_13", "Data", "homework", "TP2.csv"))
TP3<-read_csv(here("Week_13", "Data", "homework", "TP3.csv"))
TP4<-read_csv(here("Week_13", "Data", "homework", "TP4.csv"))

```

```{r}

# set up for loops

HW<-here("Week_13", "Data", "homework") # data  
files <- dir(path = HW,pattern = ".csv") # name  

# make column space for loop  
# make an empty dataframe 
 
TP_data<-tibble(filename =  rep(NA, length(files)),  # column name for year
                   mean_temp = rep(NA, length(files)), # mean temperature column
                   mean_light = rep(NA, length(files)), # mean light  
                std_temp = rep(NA, length(files)), # sd temp column  
                std_light = rep(NA, length(files)) # sd light column  
                   )

raw_data<-read_csv(paste0(HW,"/",files[1])) # test run  
head(raw_data)

```

```{r}
mean_temp<-mean(raw_data$Temp.C, na.rm = TRUE) # mean temp  
mean_light<-mean(raw_data$Intensity.lux, na.rm = TRUE) # mean light  
std_temp<-sd(raw_data$Temp.C, na.rm = TRUE) # sd temp  
std_light<-sd(raw_data$Intensity.lux, na.rm = TRUE) # sd light
```


```{r}
# Loop!

for (i in 1:length(files)){ # loop over 1:3 the number of files 
raw_data<-read_csv(paste0(HW,"/",files[i]))
TP_data$filename[i]<-files[i] # caluclate means and sd from data files  
TP_data$mean_temp[i]<-mean(raw_data$Temp.C, na.rm =TRUE) # mean temp  
TP_data$mean_light[i]<-mean(raw_data$Intensity.lux, na.rm =TRUE) # mean light 
TP_data$std_temp[i]<-sd(raw_data$Temp.C, na.rm =TRUE) # sd temp  
TP_data$std_light[i]<-sd(raw_data$Intensity.lux, na.rm =TRUE) # sd light  
} 

TP_data
```

```{r}

# maps! 

HW<-here("Week_13", "Data", "homework") # file  
files <- dir(path = HW,pattern = ".csv") # rename 
files <- dir(path = HW,pattern = ".csv", full.names = TRUE)
# or save the entire path name

```


```{r}
data<-files %>%
  set_names()%>% # set's the id of each list to the file name
  map_df(read_csv,.id = "filename") %>% # map everything to a dataframe and put the id in a column called filename
  group_by(filename) %>% # group  
  summarise(mean_temp = mean(Temp.C, na.rm = TRUE), # mean temp  
            mean_light = mean(Intensity.lux,na.rm = TRUE), # mean light  
            std_temp = sd(Temp.C, na.rm = TRUE), # sd temp  
            std_light = sd(Intensity.lux,na.rm = TRUE)) # sd light  
data
```

