---
title: "ETRmax"
author: "Kauanoe Greene"
date: "2024-11-14"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      message = FALSE, 
                      warning = FALSE, 
                      fig.path = "../Output/")
```

```{r}
# visuals
library(tidyverse)
library(dplyr)
library(tidytext)
library(here)

# models (stats)
library(lmerTest)
library (RLRsim)
library(Matrix)
# library(lme4)
library(lattice)
library(car)
library(nlme)
```

```{r}
# Data uploading
functional.phase.data <- read_csv(here("Project", "Data", "functional.phase.data.csv"))
glimpse(functional.phase.data)
view(functional.phase.data)
```


```{r}
# group control and treatment
# group by phase
# summarise mean

mean_data <- functional.phase.data %>% 
  select(Week, Population, Treatment, Chlorophyll, Conductance, ETRmax, Phase) %>% 
  group_by(Week, Population, Treatment, Phase) %>% 
  summarize(mean_chl = mean(Chlorophyll, na.rm = TRUE), 
            mean_cond = mean(Conductance, na.rm = TRUE), 
            mean_etrm = mean(ETRmax, na.rm = TRUE))

view(mean_data)
```


```{r}
# etrmax over time

etrmplot <- mean_data %>% # datasheet
  ggplot(aes(x = Week, # x-axis
             y = mean_etrm, # y-axis
             color = Treatment)) + # colors
  geom_point() +  # data points
  geom_line() +  # plot
  labs(subtitle = "Detecting intraspecific variation in plasticity of rates of ETRmax in response to drought stress", # plot subtitle
       caption = "Data sourced from: Greene 2023", # plot caption
       x = "Time (Weeks)", # x-axis label
       y = "Mean ETRmax") + # y-axis label
  ggtitle("Effects of Drought on ETRmax in 'A'ali'i") + # plot title
  facet_wrap(~Population) + # create panels for each population!
  scale_color_manual(breaks= c("C", "PD"), labels = c("Control Group", "Pulse Drought Group"), values = c("darkgreen", "brown")) + # rename legend variables
  theme(plot.title = element_text(face = "bold", color = "black", hjust = 0.5), # bold title
        axis.text.x = element_text(size = 8), axis.title.x = element_text(size = 10), # adjust x-axis labels
        axis.text.y = element_text(size = 8), axis.title.y = element_text(size = 10),   # adjust y-axis labels
        legend.position = "top", 
        plot.subtitle = element_text(size = 10, hjust = 0.5), 
        legend.title = element_blank())

# save plot to my output folder
ggsave(here("Project", "Output", "etrmplot.png")) 

# view plot
etrmplot
```


```{r cars}
# plot recovery phases

etrmphase_plot <- phase_data %>% # datasheet
  ggplot(aes(x = Phase, # x-axis
             y = mean_etrm, # y-axis
             color = Treatment)) + # colors
  geom_point() +  # data points # plot
  geom_line(aes(group = Treatment)) + 
  labs(subtitle = "Investigating the priming effects of drought treatment on ETRmax throughout recovery phases", # plot subtitle
       caption = "Data sourced from: Greene 2023", # plot caption
       x = "Recovery Phase", # x-axis label
       y = "Mean ETRmax Content") + # y-axis label
  ggtitle("Drought Priming Effect on ETRmax in 'A'ali'i") + # plot title
  facet_wrap(~Population) + # create panels for each population!
  scale_color_manual(breaks= c("C", "PD"), labels = c("Control Group", "Pulse Drought Group"), values = c("darkgreen", "brown")) + # rename legend variables
  scale_x_discrete(labels = c('Treatment', 'Pre', 'Mid', 'Post')) +
theme(plot.title = element_text(face = "bold", color = "black", hjust = 0.5), # bold title
        axis.text.x = element_text(size = 8), axis.title.x = element_text(size = 10), # adjust x-axis labels
        axis.text.y = element_text(size = 8), axis.title.y = element_text(size = 10),   # adjust y-axis labels
        legend.position = "top", 
        plot.subtitle = element_text(size = 10, hjust = 0.5), 
        legend.title = element_blank())

# save plot to my output folder
ggsave(here("Project", "Output", "etrmphase_plot.png")) 

# view plot
etrmphase_plot
```


