---
title: 'Week 09B: Working with Factors'
author: "Kauanoe Greene"
date: "2024-11-01"
output: 
  github_document:
    toc: TRUE
  
---

```{r setup, include=FALSE}

# Let us set up Rmarkdown file

knitr::opts_chunk$set(echo = TRUE, 
                      message = FALSE, 
                      warning = FALSE, 
                      fig.path = "../Output/")
```

# Libraries  
```{r Libraries}

# Packages
# install.packages("forcats")
# install.packages("janitor")

# Libraries

library(tidyverse)
library(tidytext)
library(here)
library(janitor)
library(viridis)

```

# Data: 9B Flipped Lecture 

```{r Data}
# DATA

# Data upload

# tuesdata <- tidytuesdayR::tt_load(2021, week = 7)
# income_mean<-tuesdata$income_mean

income_mean <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-02-09/income_mean.csv')
```

# Intro to Factors  

```{r Intro to Factors}

# FACTORS

# a factor is a specialized version of a character
# How we store categorical data
# Levels: values that a factor take
# Default levels are always alphabetical

fruits <- factor(c("Apple", "Grape", "Banana"))
fruits

test <- c("A", "1", "2")
as.numeric(test)

test <- factor(test) # convert to a factor
as.numeric(test)


```
```{r}

# CSV - reading them in
# read.csv(): string read in as factors
# read_csv(): strings read in as characters

```
```{r}

#check out data
glimpse(starwars)

# how many species?
starwars %>% 
  filter(!is.na(species)) %>% # get rid of the NAs
  count(species, sort = TRUE)

```

```{r}

# convert data into a factor and lumps it all together
star_counts<-starwars %>%
  filter(!is.na(species)) %>%
  mutate(species = fct_lump(species, n = 3)) %>%
  count(species)

star_counts

```

```{r}

# Reordering factors

star_counts %>%
  ggplot(aes(x = species, y = n))+
  geom_col()

```

```{r}

# reorder in order, lol.

star_counts %>%
  ggplot(aes(x = fct_reorder(species, n), y = n))+ # reorder the factor of species by n
  geom_col()

```

```{r}

# reorder, descending

star_counts %>%
  ggplot(aes(x = fct_reorder(species, n, .desc = TRUE), y = n))+ # reorder the factor of species by n
  geom_col() +
  labs(x = "Species")

```

```{r}

# reorder lineplots
# view data
glimpse(income_mean)

```

```{r}

# plot total income by year and quantile
# plot across all dollar types

total_income<-income_mean %>%
  group_by(year, income_quintile)%>%
  summarise(income_dollars_sum = sum(income_dollars))%>%
  mutate(income_quintile = factor(income_quintile)) # make it a factor

# plot - basic line plot

total_income%>%
ggplot(aes(x = year, y = income_dollars_sum, color = income_quintile))+
  geom_line()
```

```{r}

# order line plots
# use fct_reorder2
# reorders by two variables

total_income%>%
  ggplot(aes(x = year, y = income_dollars_sum, 
             color = fct_reorder2(income_quintile,year,income_dollars_sum)))+
  geom_line()+
  labs(color = "income quantile")

```

```{r}

# reorder levels in a vector

x1 <- factor(c("Jan", "Mar", "Apr", "Dec"))

x1

# set specific order of the levels

x1 <- factor(c("Jan", "Mar", "Apr", "Dec"), levels = c("Jan", "Mar", "Apr", "Dec"))

x1

```

```{r}

# subset data with factors

starwars_clean<-starwars %>% 
  filter(!is.na(species)) %>% # remove the NAs
  count(species, sort = TRUE) %>%
  mutate(species = factor(species)) %>% # make species a factor
  filter(n>3) # only keep species that have more than 3

# view it
starwars_clean

levels(starwars_clean$species)

```
```{r}

# recoing levels

starwars_clean<-starwars %>% 
  filter(!is.na(species)) %>% # remove the NAs
  count(species, sort = TRUE) %>%
  mutate(species = factor(species)) %>% # make species a factor 
  filter(n>3)  %>% # only keep species that have more than 3 
  droplevels() # drop extra levels

levels(starwars_clean$species)

```

```{r}

# continue to recode levels

starwars_clean<-starwars %>% 
  filter(!is.na(species)) %>% # remove the NAs
  count(species, sort = TRUE) %>%
  mutate(species = factor(species)) %>% # make species a factor 
  filter(n>3)  %>% # only keep species that have more than 3 
  droplevels() %>% # drop extra levels 
  mutate(species = fct_recode(species, "Humanoid" = "Human"))
starwars_clean

```

# Homework  

```{r}

# Homework

# Data set: 
# Use either intertidal.csv or intertidal_latitude.csv

# Task 1: Clean data!
# Reorder your factors into orders that make sense!
# Fix the column headers, too!
# Use the Janitor Package

# Task 2: Plot!
# Make any type of plot where one axis is a factor
# If you decide to plot tide height, order it low-high
# If you decide to plot site, order it by latitude (s-n or n-s)

```

# Data: 9B Homework

```{r}

# Data upload
# Read in csv
# intertidal dataset
data.tide <-read_csv(here("Week_09", "Data", "intertidaldata.csv"))

view(data.tide) # dataset
glimpse(data.tide) # check it out

```

```{r}

# Data upload
# Read in csv
# intertidal latitude dataset 
data.lat <-read_csv(here("Week_09", "Data", "intertidaldata_latitude.csv"))

view(data.lat) # dataset
glimpse(data.lat) # check it out
```

```{r}

# i want to join both datasets by site
# they both have sites in common

join <- inner_join(data.lat, data.tide) %>% # join the data sets by site
  drop_na() # remove the na's
glimpse(join) # check it out

```



```{r}

# clean column names and values

join_clean <- clean_names(join) # clean up the column names
glimpse(join_clean) # check it out

```

```{r}

# change characters into factors

join_clean$quadrat <- join_clean$quadrat %>% # focal column: quadrat
  factor(levels = c("Low", "Mid", "High")) %>% # factor levels
  str_replace_all(". [1]", "") # remove unwanted symbols
glimpse(join_clean) # check it out
```


```{r}

# convert characters to factors!

join_clean %>% # data set
  mutate(site = fct_lump(site)) %>% # an attempt to make site characters into factors
  mutate(quadrat = fct_lump(quadrat)) # an attempt to make quadrat characters into factors
  
```


# Plot  

```{r}

# plot!
# include a factor on one axis
# make sure the values are organized alphabetically/chronologically

anemoneplot <- join_clean %>% # data set
  select(site, quadrat, anemone, latitude) %>% # focal columns
  filter(quadrat == "High") %>% # focal quadrat
  ggplot(aes(x = anemone, # x axis value
             y = fct_reorder(site, latitude), # y axis value and organize by latitude (tried plotting on x axis but it got smooshed)
             color = site)) + # color the different sites
  geom_line() + # plot type
  geom_point() + # plot point
  labs(x = "Anemone Count", # x axis title
       y = "Site", # y axis title 
       title = "Anemone in the Intertidal Zone at High Tide") + # plot title
  theme_bw() + # theme
  theme(legend.position = "none")  # remove legend

# save plot to my output folder
ggsave(here("Week_09", "Output", "anemoneplot.png")) 

# view plot
anemoneplot

```



