---
title: 'Week 08B: Functional Programming'
author: "Kauanoe Greene"
date: "2024-10-22"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Packages
# install.packages(PNWColors)

# Libraries
library(tidyverse)
library(palmerpenguins)
library(PNWColors)
```

```{r}

df <- tibble( 
            a = rnorm(10), 
            b = rnorm(10), 
            c = rnorm(10), 
            d = rnorm(10))
head(df)
```

```{r}

df <- df %>% 
  mutate(a = (a-min(a, na.rm = TRUE))/(max(a, na.rm = TRUE)-min(a, na.rm = TRUE)))

# be careful of mistakes

df <- df %>%
  mutate(a = (a-min(a, na.rm = TRUE))/(max(a, na.rm = TRUE)-min(a, na.rm = TRUE)),
         b = (b-min(b, na.rm = TRUE))/(max(b, na.rm = TRUE)-min(b, na.rm = TRUE)),
         c = (c-min(c, na.rm = TRUE))/(max(c, na.rm = TRUE)-min(c, na.rm = TRUE)),
         d = (d-min(d, na.rm = TRUE))/(max(d, na.rm = TRUE)-min(d, na.rm = TRUE)))

# rescale
# let us write a function for this!

rescale01 <- function(x) {
  value<-(x-min(x, na.rm = TRUE))/(max(x, na.rm = TRUE)-min(x, na.rm = TRUE))
  return(value)
}

df %>%
  mutate(a = rescale01(a),
         b = rescale01(b),
         c = rescale01(c),
         d = rescale01(d))
```

```{r}
# steps to create a new function

# 1. pick a name for the new function (example: "rescale01")
# 2. list inputs or arguments (example: (x, y, z))
# 3. place code in body of the function (a block that immediately follows the function(...)) curly brackets?
# return tells us what values we want returned when you run the function


rescale01 <- function(x) {
  value<-(x-min(x, na.rm = TRUE))/(max(x, na.rm = TRUE)-min(x, na.rm = TRUE))
  return(value)
}

# 1. what is the func calculation!
# temp_C <- (temp_F - 32) * 5 / 9

# 2. name it!
# fahrenheit_to_celsius <- function() {}
fahrenheit_to_celsius <- function() { 
  temp_C <- (temp_F - 32) * 5 / 9
}

# 3. decide arguments
fahrenheit_to_celsius <- function(temp_F) {
  temp_C <- (temp_F - 32) * 5 / 9 
}

# 4. what is being returned?
fahrenheit_to_celsius <- function(temp_F) { 
  temp_C <- (temp_F - 32) * 5 / 9 
  return(temp_C)
}

# 5. TEST IT
fahrenheit_to_celsius(32)
fahrenheit_to_celsius(212)

# Think, pair, share!
# write a function converting celcius to kelvin
# kelvin is celcius + 273.15




```

```{r}
# making plots into a function

pal <- pnw_palette("Lake", 3, type = "discrete")

ggplot(penguins, aes(x = body_mass_g, y = bill_length_mm, color = island))+
  geom_point()+
  geom_smooth(method = "lm")+ # add a linear model
  scale_color_manual("Island", values=pal)+   # use pretty colors and another example of how to manually change the legend title for colors
  theme_bw()
```

```{r}
myplot<-function(data, x, y){

pal<-pnw_palette("Lake",3, type = "discrete") # color palette 

ggplot(data, aes(x = {{x}}, y = {{y}} , color = island))+
  geom_point()+
  geom_smooth(method = "lm")+ # add a linear model
  scale_color_manual("Island", values = pal)+   # use pretty colors and change the legend title
  theme_bw()
}

myplot(dat = penguins, x = body_mass_g, y = bill_length_mm)
```

```{r}
# testing plot with new variables

myplot(data = penguins, x = body_mass_g, y = flipper_length_mm)

```

```{r}
# Defaults!
# adding defaults so you do not have to state the arguments again.
# we just need to specify x and y

myplot<-function(data = penguins, x, y){

pal<-pnw_palette("Lake",3, type = "discrete") # my color palette 

ggplot(data, aes(x = {{x}}, y = {{y}} , color = island))+
  geom_point()+
  geom_smooth(method = "lm")+ # add a linear model
  scale_color_manual("Island", values = pal)+   # use pretty colors and change the legend title
  theme_bw()
}

# view plot
myplot(x = body_mass_g, y = flipper_length_mm)
```

```{r}
# Layers!
# layering the plot
# spice up the plot ^_^

myplot(x = body_mass_g, y = flipper_length_mm)+
  labs(x = "Body mass (g)",
       y = "Flipper length (mm)")
```

```{r}
# if-else!
# different conditions
# statements that allow you to have one or another outcome.

a <- 4
b <- 5

if (a > b) { # my question
  f <- 20 # if it is true give me answer 1
    } else { # else give me answer 2
  f <- 10
    }

f
```
```{r}
# back to plotting

myplot<-function(data = penguins, x, y ,lines=TRUE ){ # add new argument for lines

pal<-pnw_palette("Lake",3, type = "discrete") # my color palette 

ggplot(data, aes(x = {{x}}, y = {{y}} , color = island))+
  geom_point()+
  geom_smooth(method = "lm")+ # add a linear model
  scale_color_manual("Island", values=pal)+   # use pretty colors and change the legend title
  theme_bw()
}


# add the if-else statement now to the plot!

myplot<-function(data = penguins, x, y, lines=TRUE ){ # add new argument for lines

pal<-pnw_palette("Lake",3, type = "discrete") # my color palette 
if(lines==TRUE){

  ggplot(data, aes(x = {{x}}, y = {{y}} , color = island))+
  geom_point()+
  geom_smooth(method = "lm")+ # add a linear model
  scale_color_manual("Island", values=pal)+   # use pretty colors and change the legend title
  theme_bw()
}
else{
ggplot(data, aes(x = {{x}}, y = {{y}} , color = island))+
  geom_point()+
  scale_color_manual("Island", values=pal)+   # use pretty colors and change the legend title
  theme_bw()
}
}

# test it!

# with lines
myplot(x = body_mass_g, y = flipper_length_mm)

```

```{r}

# test the plot, again!
# without (geom_smooth) lines

myplot(x = body_mass_g, y = flipper_length_mm, lines = FALSE)
```

```{r}

# HOMEWORK
# Use any dataset you would like and make two useful functions. 
# One that is a plot and one that is not. Turn in your functions using RMarkdown with at least 2 examples per function showing its flexibility. Due, as always, at 1pm on Tuesday.

```


